/**
 * Activity Store Module
 *
 * Provides CRUD operations for activity log entries in IndexedDB.
 * Activity logs are stored locally only - NEVER synced to Supabase (FR19).
 *
 * This module runs in the renderer process and uses Dexie for IndexedDB access.
 *
 * Source: notes/architecture-electron-migration.md#ADR-008
 * Source: notes/sprint-artifacts/3-3-activity-storage-in-indexeddb.md
 */

import Dexie from 'dexie'
import { db, type ActivityLogEntry } from './db'

/**
 * Input type for saving activity entries
 * Matches the ActivityEntry type from electron/activity/types.ts
 * but without the id field (which is auto-generated by IndexedDB)
 */
export interface ActivityEntryInput {
  /** ID of the time entry this activity belongs to */
  timeEntryId: string
  /** Name of the active application */
  appName: string
  /** Title of the active window */
  windowTitle: string
  /** ISO 8601 timestamp when this activity was captured */
  timestamp: string
}

/**
 * Save activity entries to IndexedDB
 *
 * Bulk inserts entries for efficient batch storage.
 * Called when activity tracking stops to persist captured entries.
 *
 * @param entries - Array of activity entries to save (without id - auto-generated)
 * @returns Promise that resolves when all entries are saved
 *
 * @example
 * const entries = [
 *   { timeEntryId: 'entry-1', appName: 'VSCode', windowTitle: 'App.tsx', timestamp: '...' },
 *   { timeEntryId: 'entry-1', appName: 'Chrome', windowTitle: 'Google', timestamp: '...' }
 * ];
 * await saveActivityEntries(entries);
 *
 * AC-3.3.1: When activity:stop IPC is called, all captured entries are saved to IndexedDB
 */
export async function saveActivityEntries(entries: ActivityEntryInput[]): Promise<void> {
  if (entries.length === 0) {
    return
  }

  // Bulk add entries - Dexie handles auto-increment for id
  await db.activityLogs.bulkAdd(entries as ActivityLogEntry[])

  if (import.meta.env.DEV) {
    console.log(`[Today] ActivityStore: Saved ${entries.length} activity entries`)
  }
}

/**
 * Get activity entries for a specific time entry
 *
 * Retrieves all activity logs associated with the given timeEntryId,
 * sorted by timestamp ascending (oldest first).
 *
 * @param timeEntryId - The ID of the time entry to get activity for
 * @returns Promise resolving to array of activity entries (empty if none found)
 *
 * @example
 * const entries = await getActivityEntriesByTimeEntryId('entry-1');
 * // Returns: [{ id: 1, timeEntryId: 'entry-1', appName: 'VSCode', ... }, ...]
 *
 * AC-3.3.3: Entries are indexed by timeEntryId for fast retrieval
 * AC-3.3.6: activity:get-log IPC returns entries from IndexedDB
 * AC-3.3.7: Returns empty array if no activity exists for timeEntryId
 */
export async function getActivityEntriesByTimeEntryId(
  timeEntryId: string
): Promise<ActivityLogEntry[]> {
  // Use compound index [timeEntryId+timestamp] for ordered retrieval
  const entries = await db.activityLogs
    .where('[timeEntryId+timestamp]')
    .between([timeEntryId, Dexie.minKey], [timeEntryId, Dexie.maxKey])
    .toArray()

  if (import.meta.env.DEV) {
    console.log(
      `[Today] ActivityStore: Retrieved ${entries.length} entries for timeEntryId: ${timeEntryId}`
    )
  }

  return entries
}

/**
 * Delete all activity entries for a specific time entry
 *
 * Useful for cleanup when a time entry is deleted.
 *
 * @param timeEntryId - The ID of the time entry to delete activity for
 * @returns Promise resolving to the number of entries deleted
 */
export async function deleteActivityEntriesByTimeEntryId(
  timeEntryId: string
): Promise<number> {
  const count = await db.activityLogs.where('timeEntryId').equals(timeEntryId).delete()

  if (import.meta.env.DEV) {
    console.log(`[Today] ActivityStore: Deleted ${count} entries for timeEntryId: ${timeEntryId}`)
  }

  return count
}

/**
 * Get the count of activity entries for a specific time entry
 *
 * Useful for displaying activity count without loading all entries.
 *
 * @param timeEntryId - The ID of the time entry to count activity for
 * @returns Promise resolving to the count of entries
 */
export async function getActivityCountByTimeEntryId(timeEntryId: string): Promise<number> {
  return await db.activityLogs.where('timeEntryId').equals(timeEntryId).count()
}
